### ISSUE TITLE
Infinite restart loop with Dyalog 18.2

### ISSUE THREAD

**Issue by xpqz** [Dyalog/dyalog-jupyter-kernel#80]
The kernel seems to be very glitchy with 18.2. MacOS 12.0.1, latest dyalog kernel, python 3.9. 

Bad file descriptor, tcp recv, restart loop. Crash log: https://gist.github.com/xpqz/11f99b6788f9d8a0b5b9b76793f4a12e

```txt
[W 09:27:38.093 NotebookApp] Notebook learnapl/contents/trees.ipynb is not trusted
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fba843b3fa0>(<Future finis...C: 1\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fba843b3fa0>(<Future finis...C: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-79' coro=<HTTP1ServerConnection._server_request_loop() running at /opt/anaconda3/envs/py39/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...PC: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/anaconda3/envs/py39/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-69' coro=<MappingKernelManager.start_kernel() running at /opt/anaconda3/envs/py39/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/anaconda3/envs/py39/lib/python3.9/site-packages/tornado/ioloop.py:695]> is being executed.
[I 09:27:39.057 NotebookApp] Kernel started: fa4c30f4-2df5-449f-b0cd-7728e931e26a, name: dyalog-kernel
[W 09:28:00.162 NotebookApp] Replacing stale connection: fa4c30f4-2df5-449f-b0cd-7728e931e26a:bb8069a0bdb045c19d0c0feb8a3b1120
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=DyalogKernel)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 647, in initialize
    self.init_kernel()
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 499, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 264, in __init__
    self.dyalog_ride_connect()
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 160, in dyalog_ride_connect
    self.ride_receive_wait()
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 313, in ride_receive_wait
    if self.ride_receive():
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 280, in ride_receive
    head = self.recv_all(8)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 269, in recv_all
    part = self.dyalogTCP.recv(msg_len)
OSError: [Errno 9] Bad file descriptor
[I 09:28:12.056 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[W 09:28:22.177 NotebookApp] Replacing stale connection: fa4c30f4-2df5-449f-b0cd-7728e931e26a:bb8069a0bdb045c19d0c0feb8a3b1120
[W 09:28:39.127 NotebookApp] Timeout waiting for kernel_info reply from fa4c30f4-2df5-449f-b0cd-7728e931e26a
[I 09:28:39.147 NotebookApp] Starting buffering for fa4c30f4-2df5-449f-b0cd-7728e931e26a:bb8069a0bdb045c19d0c0feb8a3b1120
[I 09:28:39.152 NotebookApp] Restoring connection for fa4c30f4-2df5-449f-b0cd-7728e931e26a:bb8069a0bdb045c19d0c0feb8a3b1120
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=DyalogKernel)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 647, in initialize
    self.init_kernel()
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 499, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 264, in __init__
    self.dyalog_ride_connect()
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 160, in dyalog_ride_connect
    self.ride_receive_wait()
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 313, in ride_receive_wait
    if self.ride_receive():
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 280, in ride_receive
    head = self.recv_all(8)
  File "/opt/anaconda3/envs/py39/lib/python3.9/dyalog_kernel/kernel.py", line 269, in recv_all
    part = self.dyalogTCP.recv(msg_len)
OSError: [Errno 9] Bad file descriptor
[I 09:28:45.088 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel fa4c30f4-2df5-449f-b0cd-7728e931e26a restarted
```

**Comment by xpqz** [comment]
Can't repro
